Repository rancher/fleet-e2e, pull requests merged in 2024-10, with the labels that each got.

#211 Add remediation for flaky test 126
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fixes / refactors

#214 Adding test to check cabundle secret is not created without tls certificate
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: automation

#219 Automate keepResources via GitRepo yaml
  tests/assets/git-repo-keep-resources-true.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#220 Fleetqa/145 basic job cleanup test
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#221 Adding retry to polling disable 126
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fixes / refactors

#224 Adding more job deletion tests
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#225 Enhancing assertion on job deletion faulty case
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: fixes / refactors

#226 Update regex on rancher version to ensure 2.10 is executed
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fleet-e2e-ci

#228 Fleetqa/ci fixes and adaptation for 210
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: fixes / refactors

#229 Adding workaround for error content check on 2.10 for invalid characters
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fixes / refactors
