Repository rancher/fleet-e2e, pull requests merged in 2024-07, with the labels that each got.

#160 Return gitrepo resources checks for tests in local-fleet namespace
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: enhancement, automation

#161 Remove check on active / modified state due to new icon in 2.9
  tests/cypress/support/commands.ts
Labels: bug

#165 Refactoring of verifyTableRow
  tests/cypress/support/commands.ts
Labels: enhancement, fleet-e2e-ci

#164 Fix 2.9 tests
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: automation

#166 Adding health check on Yaml while creating Gitrepo
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: enhancement, automation

#155 Add clusterGroup test automation
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#168 Manual upgrade fleet from pre release version
  tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#170 Fixed 2.7 nav issue and 2.9 banner text with regex
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: fleet-e2e-ci, automation
