Repository rancher/fleet-e2e, pull requests merged in 2024-05, with the labels that each got.

#116 Fleet qa/60 oci helm public
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#117 Implementing test for Private OCI helm chart support GHCR
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#123 Bumping @rancher-ecp-qa/cypress-library to 1.1.0
  tests/package.json
Labels: fleet-e2e-ci

#122 Support for multiple downstream cluster provisioning
  .github/workflows/master-e2e.yaml
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
Labels: fleet-e2e-ci

#120 Add configmap test for correctDrift
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#125 Use full rancher version in QASE_RUN_NAME
  .github/workflows/master-e2e.yaml
Labels: fleet-e2e-ci

#129 Better downsteam cluster registration handling
  tests/e2e/install_test.go
Labels: bug, automation

#128 Adding RBAC test with custom roles (Fleet-5)
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-pr_rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.9.yaml
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: fleet-e2e-ci, automation

#133 Bumping gha to avoid annotation warnings
  .github/workflows/master-e2e.yaml
Labels: fleet-e2e-ci

#135 Adding more Rbac standard user tests (43 and 44) with specifc verbs
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#136 Adding rbac qase 45 list and delete std user
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: automation

#138 Stabilizing flakiness with "Edit Config" for RBAC tests
  tests/cypress/support/commands.ts
Labels: bug, fleet-e2e-ci

#139 Bumping cypress-qase-reporter to 1.4.3
  tests/package.json
Labels: fleet-e2e-ci

#137 Added RBAC FLEET-42 test automation
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation
