Repository rancher/fleet-e2e, pull requests merged in 2024-12, with the labels that each got.

#239 Fleetqa/further adjustments 152 test
  tests/assets/disable_polling.yaml
  tests/assets/webhook-tests/webhook_ingress.yaml
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: fixes / refactors

#241 Make CI 2.8 Weekly
  .github/workflows/ui-rm_head_2.8.yaml
Labels: fleet-e2e-ci

#242 Updated locator to fix 2.8 clusterGroup failures
  tests/cypress/support/commands.ts
Labels: automation

#244 Adding new testing Rancher head version lane
  .github/workflows/ui-rm_head.yaml
  README.md
Labels: fleet-e2e-ci

#243 Bumping Cypress to 13.16.0
  .github/workflows/master-e2e.yaml
  tests/package.json
Labels: fleet-e2e-ci

#247 Bump node to version 18
  .github/workflows/master-e2e.yaml
Labels: fleet-e2e-ci

#248 Skipping test 126 in 2.9 due to unfixed error
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fixes / refactors
