Repository rancher/fleet-e2e, pull requests merged in 2024-11, with the labels that each got.

#227 New CI test lane for Rancher 2.10
  .github/workflows/ui-rm_head_2.10.yaml
  README.md
Labels: fleet-e2e-ci

#230 Bump 2.10 support from ele-testhelpers
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#231 Bump ele-testhelpers
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#216 Fix Fleet-27 test case failure behavior
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: fleet-e2e-ci, automation

#233 Bump ele-testhelpers recent changes
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#236 Automated clusterGroupSelector Fleet-32 test
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#238 Fleetqa/webhook basic test
  .github/workflows/master-e2e.yaml
  tests/assets/webhook-tests/webhook_ingress.yaml
  tests/assets/webhook-tests/webhook_setup.sh
  tests/assets/webhook-tests/webhook_test_2_replicas.sh
  tests/assets/webhook-tests/webhook_test_5_replicas.sh
  tests/assets/webhook-tests/webhook_test_disable_polling.yaml
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#237 Automate clustergroup test cases Fleet-28 and Fleet-29
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation
