Repository rancher/fleet-e2e, pull requests merged in 2024-04, with the labels that each got.

#87 Add check application status to each test
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#90 Fleet qa/79 test ssh private repo
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-pr_rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.9.yaml
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/plugins/index.ts
  tests/cypress/support/commands.ts
  tests/scripts/start-cypress-tests
Labels: automation

#93 Adapt ssh locator for rancher 2.7
  tests/cypress/support/commands.ts
Labels: bug, automation

#96 Fleet qa/review implicit waits and other mechanism
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: enhancement, automation

#97 Use inputs in run-name for dispatched runs
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.9.yaml
Labels: automation

#98 Update rancher_version values for scheduled jobs
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.9.yaml
Labels: bug, automation

#88 Added test for correctDrift
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#103 Added test for existing GitRepo has keepResources
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: automation

#107 Fleet qa/login updates
  tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts
Labels: fleet-e2e-ci

#106 Enable mochawesome reporter and change several filepaths
  .github/workflows/master-e2e.yaml
  tests/cypress.config.ts
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/e2e/unit_tests/user.spec.ts
  tests/package.json
  tests/scripts/start-cypress-tests
  tests/tsconfig.json
Labels: fleet-e2e-ci

#109 update .gitignore
  .gitignore
Labels: fleet-e2e-ci

#105 Add test no change local cluster to another workspace
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#113 Adding exception to skip test for rancher 2.7
  .github/workflows/master-e2e.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: bug, fleet-e2e-ci

#115 Automation to verify Imagescan does not break fleet controller
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation
