Repository rancher/fleet-e2e, pull requests merged in 2024-06, with the labels that each got.

#142 qase reporter back to 1.4.1
  tests/package.json
Labels: bug

#141 Added toggle namespace to point to user only ns
  tests/cypress/support/commands.ts
Labels: automation

#140 Tests for FLEET-64 and FLEET-65 testing helmRepoURLRegex feature
  tests/assets/helm-server-with-auth-and-data.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#145 Automated 2 cases of GitRepoRestrictions
  tests/assets/git-repo-restrictions-allowed-target-ns.yaml
  tests/assets/git-repo-restrictions-non-exists-ns.yaml
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: automation

#144 Fleet qa/rbac std users 46 47 48 50
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#148 Fixing 2.7 ci
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: bug, fleet-e2e-ci

#147 Automate Fleet-41
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: automation

#149 Regexp support cy.verifyTableRow
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#152 Fix FLEET-79 flakiness due to residual of resource
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fleet-e2e-ci, automation

#150 Fleet qa/test force update removal
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: bug

#156 Changing assertion pr to attempt fix fleet 77
  tests/cypress/support/commands.ts
Labels: bug

#158 Fleet qa/rbac userbase fleetworkspaces
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: automation

#159 Always check resources of gitrepo by regexp
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: bug, automation
