Repository rancher/fleet-e2e, pull requests merged in 2024-03, with the labels that each got.

#64 Adding check for local cluster to be ready after rancher login
  tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts
Labels: automation

#67 Provision and import single k3d cluster
  .github/workflows/master-e2e.yaml
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
Labels: fleet-e2e-ci, automation

#66 Fleet qa/65 improve deletion and more
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#69 Add test for GitRepo name with K8s compliant name and trim bundle name for long GitRepo name
  .github/workflows/master-e2e.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: automation

#74 Use matrix instead of extra workflows
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_matrix.yaml
  README.md
Labels: automation

#75 Revert "Use matrix instead of extra workflows"
  .github/workflows/ui-rm_head_2.7.yaml
  .github/workflows/ui-rm_head_2.8.yaml
  .github/workflows/ui-rm_head_2.9.yaml
  README.md
Labels: automation

#76 Get rid of cy zombies processes in docker
  tests/scripts/start-cypress-tests
Labels: automation

#73 Automate test for 'keepResource' option
  .github/workflows/ui-pr_rm_head_2.8.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#81 Fleet version and images in report
  .github/workflows/master-e2e.yaml
Labels: enhancement, automation

#86 Adapting fleet-62 test to redis example after bugfix
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: automation

#85 Always expose k3d on the same port 64430
  tests/e2e/install_test.go
Labels: automation
