Repository rancher/fleet-e2e, pull requests merged in 2024-09, with the labels that each got.

#187 Test disable polling enabled does not sync Gitrepo (Fleet-124)
  tests/assets/disable_polling.yaml
  tests/assets/disable_polling_reset_2_replicas.sh
  tests/assets/disable_polling_setting_5_replicas.sh
  tests/cypress.config.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#188 Bumping cypress/grep plugin
  tests/package.json
Labels: fleet-e2e-ci

#186 Added new CI lane for Prime/Alpha build testing
  .github/workflows/ui-rm_prime_alpha_rc.yaml
Labels: fleet-e2e-ci

#191 Automate clusterGroupSelector test FLEET 30 and 31
  tests/assets/gitrepo-multi-app-cluster-group-selector.yaml
  tests/assets/gitrepo-single-app-cluster-group-selector.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#194 Automate disabling polling tests 125 and 126
  tests/assets/disable_polling_reset_2_replicas.sh
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: automation

#197 Bump latest ele-helpers
  .github/workflows/ui-rm_prime_alpha_rc.yaml
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#198 Bump ele helpers
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#200 Renamed constants and updated label removal
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#202 known-hosts test automation
  tests/assets/add-known-host.sh
  tests/assets/known-host-missmatch.yaml
  tests/assets/known-host.yaml
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#204 Fleetqa/142 cabundle test
  tests/assets/cabundle-file.pem
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#207 Allowing value 'Git Updating' to be valid also for 2.8 lanes
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: fixes / refactors

#208 Removing cron job from 2.7 given EOL soon.
  .github/workflows/ui-rm_head_2.7.yaml
  README.md
Labels: fixes / refactors

#209 Bump ele-testhelpers to fetch proxy updates
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci
