Repository rancher/fleet-e2e, pull requests merged in 2025-01, with the labels that each got.

#249 Updated logic of test to pass as it is in 2.9
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fleet-e2e-ci

#255 Bump lints
  tests/package.json
Labels: enhancement, fleet-e2e-ci

#253 Adding flags for memory improvements
  tests/cypress.config.ts
Labels: fleet-e2e-ci

#256 Fleetqa/check gitrepojob cleanup
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: automation

#257 Bumping node to 20
  .github/workflows/master-e2e.yaml
Labels: fleet-e2e-ci

#258 Fixing CI due to locators and other issues
  tests/cypress.config.ts
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: fleet-e2e-ci

#259 Updating version and name in pr lane
  .github/workflows/ui-pr_rm_current.yaml
Labels: fleet-e2e-ci

#260 Updated K8s version to all lanes as per support
  .github/workflows/ui-rm_head.yaml
  .github/workflows/ui-rm_head_2.10.yaml
  .github/workflows/ui-rm_head_2.9.yaml
  .github/workflows/ui-rm_prime_alpha_rc.yaml
Labels: fleet-e2e-ci

#262 fixing incorrect tag for test to be triggered on ci
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Labels: fixes / refactors

#263 Bumpling typescript and cy-veryiy-downloads dependencies
  tests/package.json
Labels: fleet-e2e-ci

#251 New CI Lane for Upgrade rancher
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-rm_head_upgrade.yaml
  tests/Makefile
  tests/cypress/e2e/unit_tests/upgrade_fleet.spec.ts
  tests/cypress/plugins/index.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
  tests/scripts/start-cypress-tests
Labels: fleet-e2e-ci
