Repository rancher/fleet-e2e, pull requests merged in 2025-04, with the labels that each got.

#303 Fix Upgrade Test: fleet-agent pod name change and individual Fleet Upgrade version check
  tests/cypress/e2e/unit_tests/upgrade_fleet.spec.ts
  tests/e2e/upgrade_test.go
Labels: automation

#305 Disabled Azure tests, shuffled Fleet-152
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: fleet-e2e-ci, automation

#307 Updated ele-testhelpers to latest
  tests/go.mod
  tests/go.sum
Labels: fleet-e2e-ci

#306 New known-host and life cycle features
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: automation

#310 Extended version check and added timeout to load element
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation

#313 Fleetqa/update knwownhost tests
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/fixtures/known_hosts
Labels: fixes / refactors

#314 Fleetqa/making polling tests resilient
  tests/assets/webhook-tests/webhook_setup.sh
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fixes / refactors
