Repository rancher/fleet-e2e, pull requests merged in 2025-05, with the labels that each got.

#315 Automate helm-app valuesFrom and valuesFiles tests
  tests/assets/helm-app-test-map-configmap.yaml
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: automation

#316 Workaround for known-host-tests
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Labels: fixes / refactors

#319 Remove the Force Update on cluster
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: automation

#320 Fleetqa/adding close popup window function
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: fixes / refactors

#312 Kubernetes Version upgrade for imported clusters
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-rm_head_upgrade.yaml
  tests/cypress/e2e/unit_tests/upgrade_fleet.spec.ts
  tests/cypress/plugins/index.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
  tests/scripts/start-cypress-tests
Labels: automation

#321 Split of P1 tests into another file with separate tag
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-rm_head.yaml
  .github/workflows/ui-rm_head_2.10.yaml
  .github/workflows/ui-rm_head_2.11.yaml
  .github/workflows/ui-rm_head_2.9.yaml
  .github/workflows/ui-rm_prime_alpha_rc.yaml
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Labels: fleet-e2e-ci, fixes / refactors

#322 Fixed tags in P1_2 file
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
Labels: automation, fixes / refactors

#323 Fleetqa/further popup window fix
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: fixes / refactors

#325 Fix disablePolling flackiness
  tests/assets/disable_polling_reset_2_replicas.sh
Labels: fixes / refactors

#326 Added Force Update on clusters to 2.9 and 2.10
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
Labels: automation, fixes / refactors

#327 Added git fetch/commit logic to script
  tests/assets/disable_polling_reset_2_replicas.sh
Labels: fixes / refactors

#328 Removing workaround calls closePopWindow after bug fix
  tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
  tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: fixes / refactors

#329 Fix rbac tests in head version
  tests/cypress/support/commands.ts
Labels: fixes / refactors

#331 Updated cron time and k3s versions
  .github/workflows/ui-rm_head.yaml
  .github/workflows/ui-rm_head_2.10.yaml
  .github/workflows/ui-rm_head_2.11.yaml
Labels: fleet-e2e-ci
