Repository rancher/fleet-e2e, pull requests merged in 2025-09, with the labels that each got.

#373 Fixing columns in ReadMe
  README.md
Labels: fleet-e2e-ci

#378 Fix 2.12 head tests
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
  tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
  tests/cypress/support/commands.ts
Labels: automation, fixes / refactors

#380 Removed default value for branch 2.10-stable
  .github/workflows/ui-rm_prime_alpha_rc.yaml
Labels: fleet-e2e-ci

#383 Fix clusterGroup 2 failed tests and clusterGroup tests added back for 2.12 via YAML.
  tests/assets/cluster-group-tests/clusterGroup.yaml
  tests/assets/cluster-group-tests/clusterGroupMultipleApps.yaml
  tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
Labels: fleet-e2e-ci, automation

#392 Refs/heads/fleet qa/several bumps
  .github/workflows/master-e2e.yaml
  tests/package.json
Labels: fleet-e2e-ci
